### ISSUE TITLE
More loading icons

### ISSUE THREAD

**Issue by madhuhc** [oliver-gomes/csswand#2]
It would be great if more developers add loading icons implemented in CSS

https://www.google.com/search?q=free+loading+icons&tbm=isch

**Comment by juanfrank7** [comment]
Speaking of loading icons, I just found this play button loading effect that looks super cool 
![Play Loader](https://user-images.githubusercontent.com/12146882/59398617-80da3a00-8d56-11e9-95f4-83890c64acfc.gif)

**Comment by oliver-gomes** [comment]
@madhuhc @juanfrank7 Thank you so much for the suggestion, I am adding it and will follow up soon.
