### ISSUE TITLE
Ripple borders effect on button 

### ISSUE THREAD

**Issue by stacoverf** [oliver-gomes/csswand#3]
I would love to see a ripple effect on button borders, don't know if it's "doable" on pure css.

Here is an example with React and the ripples INSIDE the button. I'm thinking more in a only border continuous outside ripple effect (hope that makes sense)
https://medium.com/@dhilipkmr/ripple-in-react-3162875cc9af

**Comment by oliver-gomes** [comment]
@stacoverf Hey, Thanks for the input! I love the idea. It's doable on pure CSS and definitely adding it to the app.

**Comment by stacoverf** [comment]
Awesome, will look out for it. Thanks!
