### ISSUE TITLE
Buttons not visible on landing page of website

### ISSUE THREAD

**Issue by 88pawankumarjha** [oliver-gomes/csswand#4]
Hi,

I just visited the website and I saw that there were 3 radio buttons. On selecting them, I could not see any change on my screen.
I then found out that there were buttons and loading icons which i need to scroll to see.

Can you change the layout so that the buttons are visible on the landing page without me needing to scroll down?

**Comment by oliver-gomes** [comment]
@88pawankumarjha When pressing any of the three radio buttons, it only shows the enabled effects. If you pressed the "all" radio button and you are viewing it on a tablet then you need to scroll down to see all the effects available. Can you share some screenshot if it's still a problem so i know what you are referring to exactly, Thanks!

**Comment by 88pawankumarjha** [comment]
I want to see the effects without scrolling down. It is a change request, not a bug.

**Comment by oliver-gomes** [comment]
@88pawankumarjha I don't think I am getting rid of the header at the moment. I am working on adding more effects maybe then I will think about changing the design bit. Thanks for the suggestion by the way 😃

**Comment by 88pawankumarjha** [comment]
Good that you are sure about the way ahead.
It seems you are not really a UX guy.

I'll soon try to contribute 👼
