### ISSUE TITLE
How will csswand be different from cssfx.dev?

### ISSUE THREAD

**Issue by marclundgren** [oliver-gomes/csswand#6]
How do we plan to differentiate csswand from [cssfx](https://cssfx.dev/)? As of right now, it seems like a copy.

**Comment by oliver-gomes** [comment]
@marclundgren Thank bringing the topic to light! I am adding some animations as of now, planning on to add more cool stuff beyond just simple css and hopefully it will be differentiated that way.

**Comment by marclundgren** [comment]
@oliver-gomes sounds good. What did you have in mind beyond simple css?

**Comment by oliver-gomes** [comment]
@marclundgren Added a color picker just now, will add more effects and other useful design tools.
