### ISSUE TITLE
Color Picker update the code to copy

### ISSUE THREAD

**Issue by jyash97** [oliver-gomes/csswand#7]
Hey @oliver-gomes

Great work 💯 

How about updating the code to copy based on the color picker value. What do you think?

I can give it a shot if this sounds promising enhancement.

**Comment by oliver-gomes** [comment]
@jyash97 If you mean copying the color value then that feature is already there, just press the button. Thanks!

**Comment by oliver-gomes** [comment]
@jyash97 I will think about that, thanks for suggestion 😄
