### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by codesandtags** [oliver-gomes/csswand#9]
Hi Oliver!

I would like to know, how can I contribute with this project? I really like CSS, so I'm trying to improve and practice my skills, so the best way is doing and doing.

Thanks in advance!

Edwin Torres.

**Comment by oliver-gomes** [comment]
@codesandtags Hey! Thanks for reaching out. I need to add more cool css effect so your help is appreciated.
You can start by creating a file inside effects folder, and just add your css style like "const styleNameCSS = css goes here"  then i can take care of the rest. 
Or even better if you can look at other effects file and understand code here and there, try to replicate their methodologies so it will be easier for me to add it to the main site. 
Any questions feel free to ask! 😃
